version: '3.8'
services:
  api:
    container_name: "docker-fastapi-websocket"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    volumes:
      - /Users/mohammedkhashifs/Documents/internship-3/prometheus_data/prometheus.yml:/etc/prometheus_data/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage:
